config/routes.rb
Scrip::Engine.routes.draw do
  resources :subscriptions


end

app/models/scrip/subscription.rb
module Scrip
  class Subscription < ActiveRecord::Base
    attr_accessible :subscription_type_id
  end
end

app/controllers/scrip/application_controller.rb
module Scrip
  class ApplicationController < ActionController::Base
  end
end

app/controllers/scrip/subscriptions_controller.rb
require_dependency "scrip/application_controller"

module Scrip
  class SubscriptionsController < ApplicationController
    # GET /subscriptions
    # GET /subscriptions.json
    def index
      @subscriptions = Subscription.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @subscriptions }
      end
    end
  
    # GET /subscriptions/1
    # GET /subscriptions/1.json
    def show
      @subscription = Subscription.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @subscription }
      end
    end
  
    # GET /subscriptions/new
    # GET /subscriptions/new.json
    def new
      @subscription = Subscription.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @subscription }
      end
    end
  
    # GET /subscriptions/1/edit
    def edit
      @subscription = Subscription.find(params[:id])
    end
  
    # POST /subscriptions
    # POST /subscriptions.json
    def create
      @subscription = Subscription.new(params[:subscription])
  
      respond_to do |format|
        if @subscription.save
          format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
          format.json { render json: @subscription, status: :created, location: @subscription }
        else
          format.html { render action: "new" }
          format.json { render json: @subscription.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /subscriptions/1
    # PUT /subscriptions/1.json
    def update
      @subscription = Subscription.find(params[:id])
  
      respond_to do |format|
        if @subscription.update_attributes(params[:subscription])
          format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @subscription.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /subscriptions/1
    # DELETE /subscriptions/1.json
    def destroy
      @subscription = Subscription.find(params[:id])
      @subscription.destroy
  
      respond_to do |format|
        format.html { redirect_to subscriptions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/scrip/application_helper.rb
module Scrip
  module ApplicationHelper
  end
end

app/helpers/scrip/subscriptions_helper.rb
module Scrip
  module SubscriptionsHelper
  end
end

app/views/layouts/scrip/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrip</title>
  <%= stylesheet_link_tag    "scrip/application", :media => "all" %>
  <%= javascript_include_tag "scrip/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scrip/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subscription_type_id %><br />
    <%= f.number_field :subscription_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrip/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/scrip/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Subscription type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.subscription_type_id %></td>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/scrip/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/scrip/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subscription type:</b>
  <%= @subscription.subscription_type_id %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>